create extension if not exists pgcrypto;
create table if not exists profiles (id uuid primary key default gen_random_uuid(), email text unique not null, password_hash text, first_name text not null, last_name text not null, phone text, document_number text, avatar_url text, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists roles (id uuid primary key default gen_random_uuid(), code text unique not null, name text not null, created_at timestamptz not null default now());
create table if not exists user_roles (user_id uuid references profiles(id) on delete cascade, role_id uuid references roles(id) on delete cascade, primary key (user_id, role_id));
create table if not exists user_units (user_id uuid references profiles(id) on delete cascade, unit_id uuid, primary key (user_id, unit_id));
create table if not exists units (id uuid primary key default gen_random_uuid(), name text not null, code text, type text not null default 'UNIDAD', acronym text, description text, email text, institutional_email text, phone text, is_faculty boolean not null default false, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists facilities (id uuid primary key default gen_random_uuid(), name text not null, description text, address text, reference text, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists spaces (id uuid primary key default gen_random_uuid(), facility_id uuid references facilities(id), name text not null, type text, capacity integer, floor text, location_reference text, description text, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists persons (id uuid primary key default gen_random_uuid(), first_name text not null, last_name text not null, email text, phone text, document_number text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists defenses (id uuid primary key default gen_random_uuid(), code text unique, unit_id uuid references units(id), program_uuid uuid, program_code text, program_name text, office_number text, title text not null, status text not null default 'DRAFT', modality text default 'PRESENTIAL', scheduled_date date, start_time time, estimated_end_time time, estimated_duration_minutes integer default 120, facility_id uuid references facilities(id), space_id uuid references spaces(id), virtual_platform text, virtual_url text, observations text, internal_notes text, scheduled_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists defense_participants (id uuid primary key default gen_random_uuid(), defense_id uuid references defenses(id) on delete cascade, person_id uuid references persons(id), participant_type text, role text, is_primary boolean default false, created_at timestamptz not null default now());
create table if not exists defense_reschedules (id uuid primary key default gen_random_uuid(), defense_id uuid references defenses(id) on delete cascade, previous_date timestamptz, new_date timestamptz, reason text, created_at timestamptz not null default now());
create table if not exists media (id uuid primary key default gen_random_uuid(), entity_type text not null, entity_id uuid not null, provider text not null default 'cloudflare-r2', provider_asset_id text not null, url text not null, mime_type text, file_size bigint, created_at timestamptz not null default now());
create table if not exists notifications (id uuid primary key default gen_random_uuid(), user_id uuid, defense_id uuid, type text, title text not null, message text not null, recipient_email text, recipient_name text, status text, provider text, provider_message_id text, error text, sent_at timestamptz, created_at timestamptz not null default now());
create table if not exists audit_logs (id uuid primary key default gen_random_uuid(), action text not null, entity_type text, entity_id uuid, old_values jsonb, new_values jsonb, metadata jsonb, user_id uuid, ip_address text, user_agent text, created_at timestamptz not null default now());

-- Compatibilidad para instalaciones existentes creadas con la primera versión del esquema.
alter table profiles add column if not exists phone text, add column if not exists document_number text, add column if not exists avatar_url text;
alter table units add column if not exists type text default 'UNIDAD', add column if not exists acronym text, add column if not exists description text, add column if not exists email text, add column if not exists institutional_email text, add column if not exists phone text, add column if not exists is_faculty boolean default false;
alter table facilities add column if not exists description text, add column if not exists reference text;
alter table spaces add column if not exists type text, add column if not exists floor text, add column if not exists location_reference text, add column if not exists description text;
alter table persons add column if not exists phone text, add column if not exists photo_url text;
alter table persons add column if not exists external_uuid uuid;
alter table persons add column if not exists external_id integer;
create unique index if not exists persons_external_uuid_unique on persons(external_uuid) where external_uuid is not null;
create unique index if not exists persons_document_number_unique on persons(document_number) where document_number is not null and document_number <> '';
alter table defenses add column if not exists code text, add column if not exists unit_id uuid references units(id), add column if not exists program_uuid uuid, add column if not exists program_code text, add column if not exists program_name text, add column if not exists office_number text, add column if not exists modality text default 'PRESENTIAL', add column if not exists scheduled_date date, add column if not exists start_time time, add column if not exists estimated_end_time time, add column if not exists estimated_duration_minutes integer default 120, add column if not exists facility_id uuid references facilities(id), add column if not exists space_id uuid references spaces(id), add column if not exists virtual_platform text, add column if not exists virtual_url text, add column if not exists observations text, add column if not exists internal_notes text;
alter table defense_participants add column if not exists role text, add column if not exists is_primary boolean default false;
alter table notifications add column if not exists defense_id uuid, add column if not exists type text, add column if not exists recipient_email text, add column if not exists recipient_name text, add column if not exists status text, add column if not exists provider text, add column if not exists provider_message_id text, add column if not exists error text, add column if not exists sent_at timestamptz;
alter table audit_logs add column if not exists old_values jsonb, add column if not exists new_values jsonb, add column if not exists user_id uuid, add column if not exists ip_address text, add column if not exists user_agent text;
alter table media add column if not exists sort_order integer default 0, add column if not exists created_by uuid;
insert into profiles (email, password_hash, first_name, last_name)
values ('admin@unapiquitos.edu.pe', '$2b$10$7lWJwCdtNIWzsPkR1pS1p.YLT7J8kNYbhr/5ldcNkiGgH42x7fbLa', 'Administrador', 'EPG')
on conflict (email) do nothing;
insert into roles (code, name) values ('SUPER_ADMIN', 'Super administrador'), ('ADMIN', 'Administrador'), ('VIEWER', 'Visualizador') on conflict (code) do nothing;
