import React, { useEffect, useState } from 'react';
import { Link, useLocation, useParams } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, Plus, Save, Trash2 } from 'lucide-react';
import { spacesService } from '../../../services/spaces.service';
import { facilitiesService } from '../../../services/facilities.service';
import { mediaService } from '../../../services/media.service';
import { spaceAvailabilityService, SpaceUnavailability } from '../../../services/space-availability.service';
import { Button } from '../../../components/ui/button';
import { Input } from '../../../components/ui/input';
import { Label } from '../../../components/ui/label';
import { Textarea } from '../../../components/ui/textarea';
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '../../../components/ui/dialog';
import { ConfirmModal } from '../../../components/shared/confirm-modal';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '../../../components/ui/table';

const Row = ({ title, description, children }: { title: string; description: string; children: React.ReactNode }) => <div className="grid grid-cols-[minmax(240px,0.75fr)_minmax(0,1.25fr)] gap-10 border-t border-slate-100 py-6"><div><Label className="text-sm font-semibold text-slate-900">{title}</Label><p className="mt-1 text-xs leading-5 text-slate-500">{description}</p></div><div className="pt-0.5">{children}</div></div>;
const dateInput = (offset = 0) => new Date(Date.now() + offset - new Date().getTimezoneOffset() * 60000).toISOString().slice(0, 16);

export const SpaceDetailPage: React.FC = () => {
  const { id = '' } = useParams(); const client = useQueryClient(); const availability = useLocation().pathname.endsWith('/availability');
  const { data: space } = useQuery({ queryKey: ['space', id], queryFn: () => spacesService.getSpaceById(id) }); const { data: facilities = [] } = useQuery({ queryKey: ['facilities'], queryFn: facilitiesService.getFacilities }); const { data: media = [] } = useQuery({ queryKey: ['media', 'space', id], queryFn: () => mediaService.getMediaByEntity('space', id) }); const { data: blocks = [] } = useQuery({ queryKey: ['space-unavailability', id], queryFn: () => spaceAvailabilityService.getBySpace(id) });
  const [data, setData] = useState<any>({}); const [open, setOpen] = useState(false); const [remove, setRemove] = useState<SpaceUnavailability | null>(null); const [files, setFiles] = useState<File[]>([]); const [block, setBlock] = useState({ type: 'MAINTENANCE', reason: '', starts_at: dateInput(), ends_at: '' });
  useEffect(() => { if (space) setData({ name: space.name, facility_id: space.facility_id, type: space.type, capacity: space.capacity, floor: space.floor || '', location_reference: space.location_reference || '', description: space.description || '' }); }, [space]);
  const save = useMutation({ mutationFn: () => spacesService.updateSpace(id, data), onSuccess: () => { client.invalidateQueries({ queryKey: ['space', id] }); client.invalidateQueries({ queryKey: ['spaces'] }); } });
  const create = useMutation({ mutationFn: async () => { const saved = await spaceAvailabilityService.create({ ...block, space_id: id, status: 'SCHEDULED', starts_at: new Date(block.starts_at).toISOString(), ends_at: block.ends_at ? new Date(block.ends_at).toISOString() : null, notes: null } as any); await Promise.all(files.slice(0, 3).map((file) => mediaService.uploadMedia({ entity_type: 'space_unavailability', entity_id: saved.id, file }))); }, onSuccess: () => { client.invalidateQueries({ queryKey: ['space-unavailability', id] }); setOpen(false); setFiles([]); } });
  const destroy = useMutation({ mutationFn: (item: string) => spaceAvailabilityService.remove(item), onSuccess: () => { client.invalidateQueries({ queryKey: ['space-unavailability', id] }); setRemove(null); } });
  if (!space) return <div className="p-8 text-sm text-slate-500">Cargando espacio…</div>;
  if (availability) return <div className="mx-auto max-w-5xl space-y-6"><Link to={`/admin/spaces/${id}`} className="inline-flex items-center gap-1 text-xs text-slate-500"><ArrowLeft className="h-3 w-3" />Volver a edición</Link><div><h1 className="text-2xl font-bold">Disponibilidad e historial</h1><p className="text-sm text-slate-500">Eventos que bloquean el uso del aula.</p></div><Button onClick={() => setOpen(true)}><Plus className="mr-2 h-4 w-4" />Registrar evento</Button><div className="overflow-hidden rounded-lg border bg-white"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs text-slate-500"><tr><th className="p-3">Tipo</th><th>Motivo</th><th>Inicio</th><th>Fin</th><th /></tr></thead><tbody>{[...blocks].sort((a,b) => b.created_at.localeCompare(a.created_at)).map((item) => <tr className="border-t" key={item.id}><td className="p-3 font-medium">{item.type}</td><td>{item.reason}</td><td>{new Date(item.starts_at).toLocaleString()}</td><td>{item.ends_at ? new Date(item.ends_at).toLocaleString() : 'Sin fecha de fin'}</td><td><Button variant="ghost" size="icon" onClick={() => setRemove(item)}><Trash2 className="h-4 w-4 text-rose-600" /></Button></td></tr>)}</tbody></table></div><Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-w-lg"><DialogHeader><DialogTitle>Registrar indisponibilidad</DialogTitle></DialogHeader><div className="space-y-4"><Label>Tipo<select className="mt-1 h-9 w-full rounded border px-2" value={block.type} onChange={(e) => setBlock({...block,type:e.target.value})}><option value="MAINTENANCE">Mantenimiento</option><option value="EXTERNAL_EVENT">Evento externo</option><option value="UNAVAILABLE">Inhabilitada</option><option value="RESERVED">Reserva externa</option></select></Label><Label>Inicio<Input type="datetime-local" value={block.starts_at} onChange={(e) => setBlock({...block,starts_at:e.target.value})}/></Label><Label>Fin<Input type="datetime-local" value={block.ends_at} onChange={(e) => setBlock({...block,ends_at:e.target.value})}/></Label><Label>Motivo<Input value={block.reason} onChange={(e) => setBlock({...block,reason:e.target.value})}/></Label><Label>Evidencias opcionales (máximo 3)<Input type="file" multiple accept="image/*" onChange={(e) => setFiles(Array.from(e.target.files || []).slice(0,3))}/><p className="mt-1 text-xs text-slate-500">{files.length}/3 archivos seleccionados</p></Label></div><DialogFooter><Button disabled={!block.reason || create.isPending} onClick={() => create.mutate()}>Guardar</Button></DialogFooter></DialogContent></Dialog><ConfirmModal open={!!remove} onOpenChange={(value) => !value && setRemove(null)} title="Eliminar evento" description="Se quitará este bloqueo del historial." variant="destructive" onConfirm={() => remove && destroy.mutate(remove.id)}/></div>;
  return <div className="mx-auto max-w-5xl space-y-7"><Link to="/admin/spaces" className="inline-flex items-center gap-1 text-xs text-slate-500"><ArrowLeft className="h-3 w-3" />Volver a espacios</Link><div><h1 className="text-2xl font-bold text-slate-900">Editar espacio</h1><p className="text-sm text-slate-500">Actualiza la información y multimedia institucional.</p></div><section><h2 className="text-base font-semibold">Información general</h2><p className="mb-3 text-sm text-slate-500">Datos utilizados para identificar y asignar el aula.</p><div className="rounded-lg border bg-white px-5"><Row title="Nombre del espacio" description="Nombre visible en la agenda y selector de sustentaciones."><Input value={data.name || ''} onChange={(e) => setData({...data,name:e.target.value})}/></Row><Row title="Sede" description="Ubicación institucional donde está el espacio."><select className="h-9 w-full rounded border px-2" value={data.facility_id || ''} onChange={(e) => setData({...data,facility_id:e.target.value})}>{facilities.map((f) => <option key={f.id} value={f.id}>{f.name}</option>)}</select></Row><Row title="Capacidad" description="Número máximo recomendado de asistentes."><Input type="number" value={data.capacity || ''} onChange={(e) => setData({...data,capacity:Number(e.target.value)})}/></Row><Row title="Descripción" description="Equipamiento, condiciones o indicaciones del aula."><Textarea value={data.description || ''} onChange={(e) => setData({...data,description:e.target.value})}/></Row><div className="py-5"><Button onClick={() => save.mutate()}><Save className="mr-2 h-4 w-4"/>Guardar cambios</Button></div></div></section><section><h2 className="text-base font-semibold">Multimedia</h2><p className="mb-3 text-sm text-slate-500">Fotografías opcionales de infraestructura.</p><div className="rounded-lg border bg-white p-5"><label className="inline-flex cursor-pointer rounded border px-3 py-2 text-sm">Subir foto<input className="hidden" type="file" accept="image/*" onChange={(e) => e.target.files?.[0] && mediaService.uploadMedia({entity_type:'space',entity_id:id,file:e.target.files[0]}).then(() => client.invalidateQueries({queryKey:['media','space',id]}))}/></label><div className="mt-4 grid grid-cols-3 gap-3">{media.map((image) => <img key={image.id} className="h-24 w-full rounded object-cover" src={image.url}/>)}</div></div></section></div>;
};
